### ISSUE TITLE
Can I deploy this in OpenShift ?

### ISSUE THREAD

**Issue by kirangonella** [wrike/callisto#1]
Hi,

I am looking for a similar solution and this solution (Callisto) seems promising. 

I want to implement this in OpenShift. Do suggest if this support and you already had an example.

Thank you,
Kiran.

**Comment by dm3ch** [comment]
@kirangonella I haven't tested Callisto on openshift but as far as I understand you can run it (but with some problems).

1) OpenShift 3 supports all used manifests (services, pods, deploymets, rbac) and not modifies api versions, so you should be able to start callisto and callisto should be able to start pods.
2) Our callisto chart uses ingress resource that is not supported by openshift 3. So there's two options: first, modify chart to use openshift routes instead ingress resources; second, use openshift 4 that supports ingress resources (and install some ingress controller)
3) The main problem with openshift i think would be PosSecurityPolicy. By default openshift hardening PSP to not let run applications in containers as root, but you can change this behaviour.

**Comment by venkatakgonela** [comment]
Hi,

Thank you for providing the detailed feedback. I'll go with manual deployment for this time and will keep a tab on this project going further as well.

Please do suggest the road map of this project so that I will try to involve myself in this if I can be of any help.

Regards,
Kiran.

**Comment by levsha932** [comment]
We don't have particular roadmap on this because it's just work for us and cover particular scenario for quite some time with out changes. We potentially can decide to include other similar protocols like chrome dev tools and Playwright
