### ISSUE TITLE
Devtools support

### ISSUE THREAD

**Issue by yevgeniy-mikhailov** [wrike/callisto#10]
Hey guys,
Does Callisto support devtools or other connection via ws?
Case:
- connect Playwright to a browser pod for downloading remote files
- connect via CDP to intercept requests

Seems, selenoid has same one https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java#L52C9-L52C18
and it was expected to see same in Callisto

**Comment by srntqn** [comment]
Hi, @yevgeniy-mikhailov! We have an ongoing discussion within the organisation about this feature, will keep you posted.

**Comment by srntqn** [comment]
@yevgeniy-mikhailov for now we don't have plans to work on Web sockets support in Callisto. But It's still a part of our backlog so we can reconsider our priorities in the future.

**Comment by yevgeniy-mikhailov** [comment]
@srntqn Hi. Got it. Thank you for answering!
