### ISSUE TITLE
[Question] What is the status? Do you have a roadmap?

### ISSUE THREAD

**Issue by denis-domanskii** [wrike/callisto#2]
Hi Wrike folks! 

Could you please clarify a status of the project? I see 4 commits, no PR, no dev for last 2 months. Do you have a roadmap for feature releases? Or this project is freeze?

For example do you have any plans to support [Playwright](https://playwright.dev/)?

**Comment by dm3ch** [comment]
About Playwright:
Suddenly I'm not familiar with that and I haven't found detailed description yet.

But if it's uses selenium API (create/delete session) to connect to the browser - then work with playwright should be possible i think.

Callisto is pretty simple tool that just creates browser pods (on selenium create session api call) and then just proxies all requests to that session to browser as is (as far as I know). Also it handles session delete api call to stop browser pod.

We at Wrike currently heavily using it, but development is not active cause we haven't got any features that we are missing.
I think our developers will provide roadmap in future.

P.S. I'm a guy from devops wrike team, but I'm not the guy that is developing that, so I could said something not right

**Comment by levsha932** [comment]
This solution is totally alive and let us run hundreds of thousands selenium tests per day inside Wrike. But realy this simple solution just does its job well and we don't update it constantly.
We don't use Playwright (MS testing tool) as well as CromeDevTool protocol now, but we are following these two approaches to apply them when needed.
It's not difficult to proxy another protocol to pods. We'll probably do that as long as those tools will provide some extra capabilities for us. We'll discuss that cause we are considering Playwright for one of the purposes in QA.

Any contribution is also welcome.
