### ISSUE TITLE
[Query] How to run all browsers in a single Callisto cluster? 

### ISSUE THREAD

**Issue by vigneshfourkites** [wrike/callisto#4]
i have tried to launch a chrome instance and below is my values.yaml file.,

browser:
name: "chrome"
chromeImage: "browsers/chrome:89.0"
firefoxImage: "browsers/firefox:87.0"
edgeImage: "browsers/edge:91.0"
firefoxWebdriverPath: "/wd/hub" #

In the mean time, i am trying to start a Firefox instance in the cluster and it throws error.
http://172.17.0.8:4444/session returned 400 status code >>> {"tid": "web-0ced3e384e834d0c94178e9cba9947e1"}

For each browser we need to setup different cluster? Is my understanding correct?

**Comment by levsha932** [comment]
Yes the whole idea of Callisto is that you don't need this claster up and running all the time. You start it up for each build so you can set properties of Callisto for that particular build. It doesn't cost noticable time and it saves money.

**Comment by vigneshfourkites** [comment]
Got it! My case will be running 4 test of chrome, 1 test of firefox, 2 test of edge in a single test suite! This is not feasible and need to setup different cluster! Thanks a lot for the response @levsha932
