### ISSUE TITLE
Can not upload a file using Callisto

### ISSUE THREAD

**Issue by baflQA** [wrike/callisto#6]
Hi! 
I'm using Selenium 4.1.2 and the most recent Callisto version with Chrome 97 Selenoid image.

I have a given test:
```
@Test
    public void uploadTest() throws IOException {
        ChromeOptions options = new ChromeOptions();
        options.setCapability("name", "test");
        RemoteWebDriver webDriver = new RemoteWebDriver(new URL("https://your.callisto.instance.url"), options);
        webDriver.get("https://the-internet.herokuapp.com/upload");
        webDriver.setFileDetector(new LocalFileDetector());
        WebDriverWait wait = new WebDriverWait(webDriver, Duration.ofSeconds(10));
        wait.until(driver -> driver.findElement(By.className("dz-hidden-input")))
                .sendKeys("/path/to/file.png");
    }
```
This test fails with the given error:
```
org.openqa.selenium.UnsupportedCommandException: unknown command: unknown command: session/fb8d64450dcfe3d53fb5ba1b4d89bdfa/se/file
```

Could You please assist on how to overcome this issue?

**Comment by vpokotilov** [comment]
@baflQA Hi!
Unfortunately I have no experience with either Selenium 4 or Java and I don't know how to run your test.

There may be a problem with this test. Do other tests work for you, or does nothing work at all?

**Comment by baflQA** [comment]
Hi @vpokotilov 
It doesn't work only if running against callisto AND Selenium 4. 
It is passing when running against Selenium 3 grid using both Se3 and Se4, also passes when running against Callisto using Se3.
Would it be possible for You to create such a simple test using the bindings that You are familiar with?
Doesn't it look like some endpoint is not supported by the Callisto nginx?

**Comment by baflQA** [comment]
@vpokotilov looks like Callisto is not Selenium 4 compliant. I got this info from one of the Se maintainers:
```
The upload endpoint is not w3c compliant, so selenium changed the endpoint it uses to one with a selenium namespace for using it with Selenium Grid. If it is an implementation of Selenium Grid, it needs to add support for the updated routes (and there are a bunch of new ones as well).
```
are You considering supporting Se4 by Callisto?

**Comment by vpokotilov** [comment]
@baflQA thanks for the extra info.

Callisto should be W3C compliant, so we'll fix it if we can reproduce the error ;)

**Comment by vpokotilov** [comment]
@baflQA Issue was fixed [here](https://github.com/wrike/callisto-chart/commit/a028c13f59407f3c49fe5aa37ae45253cd3aaa44), please update your chart.

More information about the problem can be found [here](https://github.com/aerokube/selenoid/issues/1079).
