### ISSUE TITLE
I don't understand how to configure test launch

### ISSUE THREAD

**Issue by korpus95** [wrike/callisto#7]
Tell me how to connect to a running callisto session from tests? Could you add some example preferably on java? I use selenide and I don't understand how to run tests on a raised callisto :(

**Comment by srntqn** [comment]
Hi, @korpus95! 

Maybe this small example can be helpful:

https://github.com/wrike/callisto-chart/issues/3#issuecomment-873178395

You just need to create a new session and then communicate with Webdriver using Java selenium library.

**Comment by korpus95** [comment]
> Привет,@korpus95!
> 
> Может быть, этот небольшой пример может быть полезен:
> 
> [wrike/callisto-chart#3 (комментарий)](https://github.com/wrike/callisto-chart/issues/3#issuecomment-873178395)
> 
> Вам просто нужно создать новый сеанс, а затем связаться с Webdriver, используя библиотеку Java selenium.

it's still not very clear which URL to specify in this case?
and did I understand correctly that I have to create the session manually?

![image](https://user-images.githubusercontent.com/48594940/232806021-ed379252-f9ab-4908-a980-eda13ebacee6.png)
